# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f28505399cce0578f64a7ac297ffe3b5ac29e76035e5f4ea0d7176bf2bbfdc8be0c8bad2c88cf69c70d1f065fa6e8889877924c72ec7373cd44ccfec527ac20a

test:
  secret_key_base: 490f9dc7c9ca344fa6d753442b7dccbd39bc913d525b2f628442c1711932519afc3b5ead511070a1faefc8c0e4531457b68b57ab5019e14b255b1b51373b462a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
